/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_shun_gao_jnicallback_Native */

#ifndef _Included_test_shun_gao_jnicallback_Native
#define _Included_test_shun_gao_jnicallback_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_shun_gao_jnicallback_Native
 * Method:    registerCallback
 * Signature: (Ltest/shun/gao/jnicallback/JavaCallback;)V
 */
JNIEXPORT void JNICALL Java_test_shun_gao_jnicallback_Native_registerCallback
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
